---



- name: Test
  command: "kubectl get nodes -o wide"
  register: out
  become: no

- name: Debug
  debug: var=out



- name: Download Calico YAML
  get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ CALICO_VERSION }}/manifests/calico.yaml"
    dest: "{{ HOME_DIR }}/calico.yaml"

- name: Apply Calico Network
  command: kubectl apply -f "{{ HOME_DIR }}/calico.yaml"
  become: no

- name: Test
  command: "kubectl get pods -A"
  register: out
  become: no

- name: Debug
  debug: var=out


