---
    
- name: Extract the join command
  become: true
  command: "kubeadm token create --print-join-command"
  register: join_command

- name: show join command
  debug:
    var: join_command
     
- name: Save kubeadm join command for cluster
  local_action: copy content={{ join_command.stdout_lines | last | trim }} dest={{ join_command_location }} # defaults to your local cwd/join_command.out
